# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-10 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
